//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cineplus
{
    using Cineplus.Controllers;
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.Rankings = new HashSet<Ranking>();
        }
        public String Ranker(int xd) => "" + new RankingsController().Rankear(xd, IDPelicula);
        public String Ranker1 => "" + new RankingsController().Rankear(3, IDPelicula);
        public String Ranker2 => "" + new RankingsController().Rankear(3, IDPelicula);
        public String Ranker3 => "" + new RankingsController().Rankear(3, IDPelicula);
        public String Ranker4 => "" + new RankingsController().Rankear(5, IDPelicula);
        public String Ranker5 => "" + new RankingsController().Rankear(5, IDPelicula);
        public String getImage => "data:image/jpg;base64," + Convert.ToBase64String(Poster);
        public int IDPelicula { get; set; }
        public byte[] Poster { get; set; }
        public string Titulo { get; set; }
        public string Sinopsis { get; set; }
        public string Director { get; set; }
        public string Genero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranking> Rankings { get; set; }
    }
}
