//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cineplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int IDRanking { get; set; }
        public int IDPelicula { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public Nullable<int> NoVotos { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
    }
}
