insert into Cine..Ranking values(1,'Boleto de fuga',1,1)
insert into Cine..Ranking values(2,'Assassins Creed',1,1)
insert into Cine..Ranking values(3,'La Sirenita',1,1)
insert into Cine..Ranking values(4,'Blancanieves',1,1)
insert into Cine..Ranking values(5,'La bella y la bestia',1,1)
insert into Cine..Ranking values(6,'Ceniciente',1,1)
insert into Cine..Ranking values(7,'Rapidos y Furiosos',1,1)
insert into Cine..Ranking values(8,'Peter Pan',1,1)
insert into Cine..Ranking values(9,'Iron Man',1,1)
insert into Cine..Ranking values(10,'Iron Man 2',1,1)
insert into Cine..Ranking values(11,'Iron Man 3',1,1)
insert into Cine..Ranking values(12,'Black Panther',1,1)
insert into Cine..Ranking values(13,'Thor Ragnarok',1,1)
insert into Cine..Ranking values(14,'Thor',1,1)
insert into Cine..Ranking values(15,'Guardianes de la Galaxia',1,1)
